import { DashboardSummary, Project, AnomalyItem, RiskCase, Contractor, District } from '../types';

export const MOCK_PROJECTS: Project[] = [
  {
    _id: 'proj-1',
    projectId: 'MPLAD-2024-KA-BEL-01615',
    title: 'Installation and Development of Irrigation & Rural Electrification',
    description: 'Solar irrigation pump sets and sub-station line extension across rural blocks.',
    category: 'Irrigation & Rural Electrification',
    state: 'Karnataka',
    district: 'Belagavi',
    constituency: 'Belagavi North',
    mpName: 'Mangal Suresh Angadi',
    financialYear: '2024-2025',
    allocatedAmount: 10200000,
    utilizedAmount: 10200000,
    progress: 12,
    status: 'IN_PROGRESS',
    contractorName: 'Modern Civic Developers',
    approvalDate: '2024-11-20',
    riskScore: 91,
    riskLevel: 'CRITICAL',
    confidenceScore: 0.94,
    dimensionScores: {
      financial: 95,
      contractor: 92,
      duplicate: 45,
      geographic: 60,
      temporal: 88,
      efficiency: 92,
      dataQuality: 95,
    },
    signals: [
      {
        ruleId: 'FIN_01',
        dimension: 'FINANCIAL',
        signal: '100% Fund Disbursed vs 12% Physical Progress',
        severity: 'CRITICAL',
        explanation: 'Extreme disbursement divergence with 100% funds released prior to foundation audit.',
      },
    ],
    similarProjects: [],
    recommendation: 'Immediate physical audit and bank account freeze recommendation.',
    createdAt: '2024-11-20',
  },
  {
    _id: 'proj-2',
    projectId: 'MPLAD-2024-GU-RAJ-03315',
    title: 'Installation and Development of Education Infrastructure',
    description: 'Construction of additional classrooms and digital smart labs.',
    category: 'Education Infrastructure',
    state: 'Gujarat',
    district: 'Rajkot',
    constituency: 'Rajkot',
    mpName: 'Parshottam Rupala',
    financialYear: '2024-2025',
    allocatedAmount: 10200000,
    utilizedAmount: 10200000,
    progress: 28,
    status: 'IN_PROGRESS',
    contractorName: 'Modern Civic Developers',
    approvalDate: '2024-12-05',
    riskScore: 91,
    riskLevel: 'CRITICAL',
    confidenceScore: 0.93,
    dimensionScores: {
      financial: 92,
      contractor: 96,
      duplicate: 50,
      geographic: 40,
      temporal: 85,
      efficiency: 90,
      dataQuality: 92,
    },
    signals: [
      {
        ruleId: 'CON_02',
        dimension: 'CONTRACTOR',
        signal: 'Vendor Monopolistic Concentration Cluster',
        severity: 'CRITICAL',
        explanation: 'Modern Civic Developers holds over 65% of allocated funds in Rajkot district.',
      },
    ],
    similarProjects: [],
    recommendation: 'Mandatory cross-district contractor network investigation.',
    createdAt: '2024-12-05',
  },
  {
    _id: 'proj-3',
    projectId: 'MPLAD-2022-KA-MAN-01105',
    title: 'Installation and Development of Roads, Pathways & Bridges',
    description: 'Concrete pathway overlay and bridge culvert repair in coastal hamlets.',
    category: 'Roads, Pathways & Bridges',
    state: 'Karnataka',
    district: 'Mangaluru',
    constituency: 'Dakshina Kannada',
    mpName: 'Nalin Kumar Kateel',
    financialYear: '2022-2023',
    allocatedAmount: 8500000,
    utilizedAmount: 8500000,
    progress: 28,
    status: 'DELAYED',
    contractorName: 'Hindustan Building Solutions',
    approvalDate: '2022-08-14',
    riskScore: 91,
    riskLevel: 'CRITICAL',
    confidenceScore: 0.91,
    dimensionScores: {
      financial: 90,
      contractor: 88,
      duplicate: 82,
      geographic: 55,
      temporal: 94,
      efficiency: 89,
      dataQuality: 90,
    },
    signals: [
      {
        ruleId: 'EFF_03',
        dimension: 'EFFICIENCY',
        signal: 'Stalled Project Delay Over 24 Months',
        severity: 'CRITICAL',
        explanation: 'Work stalled at 28% progress despite full financial allocation 2 years ago.',
      },
    ],
    similarProjects: [],
    recommendation: 'Escalate to District Collectorate for contractor penalty enforcement.',
    createdAt: '2022-08-14',
  },
  {
    _id: 'proj-4',
    projectId: 'MPLAD-2023-MA-PUN-03238',
    title: 'Installation and Development of Public Health & Wellness',
    description: 'Construction of Sub-District Primary Health Center and oxygen plant.',
    category: 'Public Health & Wellness',
    state: 'Maharashtra',
    district: 'Pune',
    constituency: 'Pune',
    mpName: 'Murlidhar Mohol',
    financialYear: '2023-2024',
    allocatedAmount: 8500000,
    utilizedAmount: 8500000,
    progress: 12,
    status: 'IN_PROGRESS',
    contractorName: 'Ganga Infratech Projects',
    approvalDate: '2023-10-10',
    riskScore: 91,
    riskLevel: 'CRITICAL',
    confidenceScore: 0.95,
    dimensionScores: {
      financial: 94,
      contractor: 90,
      duplicate: 75,
      geographic: 60,
      temporal: 92,
      efficiency: 91,
      dataQuality: 94,
    },
    signals: [],
    similarProjects: [],
    recommendation: 'Conduct statutory financial audit of vendor disbursements.',
    createdAt: '2023-10-10',
  },
  {
    _id: 'proj-5',
    projectId: 'MPLAD-2022-KA-BEL-04845',
    title: 'Installation and Development of Skill Development Centers',
    description: 'Establishment of vocational training labs and computer center.',
    category: 'Skill Development Centers',
    state: 'Karnataka',
    district: 'Belagavi',
    constituency: 'Belagavi',
    mpName: 'Jagadish Shettar',
    financialYear: '2022-2023',
    allocatedAmount: 6800000,
    utilizedAmount: 6800000,
    progress: 12,
    status: 'DELAYED',
    contractorName: 'Hindustan Building Solutions',
    approvalDate: '2022-03-29',
    riskScore: 91,
    riskLevel: 'CRITICAL',
    confidenceScore: 0.96,
    dimensionScores: {
      financial: 95,
      contractor: 92,
      duplicate: 80,
      geographic: 65,
      temporal: 96,
      efficiency: 94,
      dataQuality: 96,
    },
    signals: [],
    similarProjects: [],
    recommendation: 'Prioritize physical inspection and verify asset deployment.',
    createdAt: '2022-03-29',
  },
  {
    _id: 'proj-6',
    projectId: 'MPLAD-2021-UT-KAN-04420',
    title: 'Installation and Development of Community Asset & Halls',
    description: 'Multi-purpose panchayat community hall and public library.',
    category: 'Community Asset & Halls',
    state: 'Uttar Pradesh',
    district: 'Kanpur Nagar',
    constituency: 'Kanpur',
    mpName: 'Ramesh Awasthi',
    financialYear: '2021-2022',
    allocatedAmount: 6800000,
    utilizedAmount: 6800000,
    progress: 20,
    status: 'DELAYED',
    contractorName: 'Shree Ganesh Infraprojects Pvt Ltd',
    approvalDate: '2021-09-18',
    riskScore: 87,
    riskLevel: 'CRITICAL',
    confidenceScore: 0.90,
    dimensionScores: {
      financial: 88,
      contractor: 85,
      duplicate: 60,
      geographic: 50,
      temporal: 90,
      efficiency: 88,
      dataQuality: 90,
    },
    signals: [],
    similarProjects: [],
    recommendation: 'Issue notice to contractor and evaluate work cancellation.',
    createdAt: '2021-09-18',
  },
  {
    _id: 'proj-7',
    projectId: 'MPLAD-2024-MH-NGP-00412',
    title: 'Pipelined Water Supply Scheme & Filtration Plant',
    description: 'Sub-surface water intake and pipeline distribution across 4 villages.',
    category: 'Drinking Water & Sanitation',
    state: 'Maharashtra',
    district: 'Nagpur',
    constituency: 'Nagpur',
    mpName: 'Nitin Gadkari',
    financialYear: '2024-2025',
    allocatedAmount: 14500000,
    utilizedAmount: 11200000,
    progress: 78,
    status: 'IN_PROGRESS',
    contractorName: 'Vidarbha Infra Developers',
    approvalDate: '2024-05-12',
    riskScore: 35,
    riskLevel: 'MEDIUM',
    confidenceScore: 0.94,
    dimensionScores: {
      financial: 30,
      contractor: 35,
      duplicate: 15,
      geographic: 20,
      temporal: 40,
      efficiency: 30,
      dataQuality: 96,
    },
    signals: [],
    similarProjects: [],
    recommendation: 'Normal project execution - track scheduled completion.',
    createdAt: '2024-05-12',
  },
  {
    _id: 'proj-8',
    projectId: 'MPLAD-2023-TN-CHN-00891',
    title: 'Smart Class Computers & High-Speed Optical Fiber Network',
    description: 'Hardware provisioning and network cabling for high schools.',
    category: 'Education Infrastructure',
    state: 'Tamil Nadu',
    district: 'Chennai',
    constituency: 'Chennai Central',
    mpName: 'Dayanidhi Maran',
    financialYear: '2023-2024',
    allocatedAmount: 5400000,
    utilizedAmount: 5400000,
    progress: 100,
    status: 'COMPLETED',
    contractorName: 'Vanguard Engineering Works',
    approvalDate: '2023-04-18',
    riskScore: 18,
    riskLevel: 'LOW',
    confidenceScore: 0.98,
    dimensionScores: {
      financial: 15,
      contractor: 12,
      duplicate: 10,
      geographic: 10,
      temporal: 15,
      efficiency: 18,
      dataQuality: 99,
    },
    signals: [],
    similarProjects: [],
    recommendation: 'Verified completed asset - audit closed.',
    createdAt: '2023-04-18',
  },
];

export const MOCK_DASHBOARD_SUMMARY: DashboardSummary = {
  kpis: {
    totalProjects: 5200,
    totalAllocatedAmount: 11732000000,
    totalUtilizedAmount: 8486000000,
    avgRiskScore: 24.8,
    criticalRiskCount: 29,
    highRiskCount: 240,
    mediumRiskCount: 146,
    lowRiskCount: 4785,
    totalContractors: 84,
    totalAnomalies: 269,
    openRiskCases: 21,
  },
  charts: {
    riskDistribution: [
      { name: 'Low (0-29)', count: 4785, color: '#10b981' },
      { name: 'Medium (30-59)', count: 146, color: '#f59e0b' },
      { name: 'High (60-79)', count: 240, color: '#f97316' },
      { name: 'Critical (80-100)', count: 29, color: '#ef4444' },
    ],
    categoryBreakdown: [
      { category: 'Drinking Water & Sanitation', count: 1420, totalAllocated: 3450000000, avgRisk: 22 },
      { category: 'Skill Development Centers', count: 680, totalAllocated: 1850000000, avgRisk: 34 },
      { category: 'Education Infrastructure', count: 1150, totalAllocated: 2400000000, avgRisk: 26 },
      { category: 'Sports & Youth Facilities', count: 450, totalAllocated: 980000000, avgRisk: 21 },
      { category: 'Public Health & Wellness', count: 520, totalAllocated: 1250000000, avgRisk: 42 },
      { category: 'Community Asset & Halls', count: 480, totalAllocated: 1100000000, avgRisk: 31 },
      { category: 'Roads, Pathways & Bridges', count: 320, totalAllocated: 480000000, avgRisk: 38 },
      { category: 'Irrigation & Rural Electrification', count: 180, totalAllocated: 222000000, avgRisk: 45 },
    ],
    districtRisk: [
      { state: 'Karnataka', district: 'Belagavi', projectCount: 340, totalAllocated: 920000000, avgRisk: 54, highRiskCount: 28 },
      { state: 'Gujarat', district: 'Rajkot', projectCount: 280, totalAllocated: 780000000, avgRisk: 48, highRiskCount: 22 },
      { state: 'Maharashtra', district: 'Pune', projectCount: 510, totalAllocated: 1450000000, avgRisk: 32, highRiskCount: 18 },
      { state: 'Uttar Pradesh', district: 'Kanpur Nagar', projectCount: 420, totalAllocated: 1120000000, avgRisk: 41, highRiskCount: 24 },
      { state: 'Tamil Nadu', district: 'Chennai', projectCount: 390, totalAllocated: 890000000, avgRisk: 19, highRiskCount: 6 },
    ],
    spendingByYear: [
      { year: '2021-22', allocated: 2800000000, utilized: 2650000000, count: 1200 },
      { year: '2022-23', allocated: 3400000000, utilized: 3100000000, count: 1500 },
      { year: '2023-24', allocated: 3800000000, utilized: 3200000000, count: 1650 },
      { year: '2024-25', allocated: 1732000000, utilized: 848600000, count: 850 },
    ],
  },
  topHighRiskProjects: MOCK_PROJECTS.filter((p) => p.riskLevel === 'CRITICAL' || p.riskLevel === 'HIGH'),
};

export const MOCK_ANOMALIES: AnomalyItem[] = [
  {
    _id: 'anom-1',
    anomalyId: 'ANOM-2024-01615',
    projectId: MOCK_PROJECTS[0]._id,
    projectTitle: MOCK_PROJECTS[0].title,
    state: MOCK_PROJECTS[0].state,
    district: MOCK_PROJECTS[0].district,
    category: MOCK_PROJECTS[0].category,
    contractorName: MOCK_PROJECTS[0].contractorName,
    dimension: 'FINANCIAL',
    ruleId: 'FIN_01',
    signal: '100% Fund Disbursed vs 12% Physical Progress',
    severity: 'CRITICAL',
    score: 91,
    explanation: 'Extreme disbursement divergence with 100% funds released prior to foundation audit.',
    hasInvestigationCase: true,
    riskCaseId: 'case-101',
    createdAt: '2024-11-20',
  },
  {
    _id: 'anom-2',
    anomalyId: 'ANOM-2024-03315',
    projectId: MOCK_PROJECTS[1]._id,
    projectTitle: MOCK_PROJECTS[1].title,
    state: MOCK_PROJECTS[1].state,
    district: MOCK_PROJECTS[1].district,
    category: MOCK_PROJECTS[1].category,
    contractorName: MOCK_PROJECTS[1].contractorName,
    dimension: 'CONTRACTOR',
    ruleId: 'CON_02',
    signal: 'Vendor Monopolistic Concentration Cluster',
    severity: 'CRITICAL',
    score: 91,
    explanation: 'Modern Civic Developers holds over 65% of allocated funds in Rajkot district.',
    hasInvestigationCase: true,
    riskCaseId: 'case-102',
    createdAt: '2024-12-05',
  },
];

// Rich Cases across ALL 5 Kanban Columns (OPEN, UNDER_REVIEW, VERIFIED, DISMISSED, ESCALATED)
export const MOCK_RISK_CASES: RiskCase[] = [
  // OPEN COLUMN (4 Cases)
  {
    _id: 'case-101',
    caseId: 'CASE-2024-KA-001',
    projectId: MOCK_PROJECTS[0]._id,
    projectTitle: MOCK_PROJECTS[0].title,
    category: MOCK_PROJECTS[0].category,
    state: 'Karnataka',
    district: 'Belagavi',
    contractorName: 'Modern Civic Developers',
    allocatedAmount: 10200000,
    riskScore: 91,
    priority: 'CRITICAL',
    status: 'OPEN',
    assignedToEmail: 'auditor@mplad-insight.demo',
    assignedToName: 'Priya Iyer (Senior Auditor)',
    initialFlagReasons: ['100% Fund Disbursed vs 12% Physical Progress', 'Vendor Monopolistic Concentration'],
    notes: [
      {
        noteId: 'note-101',
        authorEmail: 'system@mplad-insight.demo',
        authorName: 'AI Risk Engine',
        authorRole: 'ANALYST',
        content: 'Case automatically registered from Isolation Forest multivariate cost divergence detector.',
        createdAt: '2024-11-21T09:00:00Z',
      },
    ],
    createdAt: '2024-11-21',
    updatedAt: '2024-11-21',
  },
  {
    _id: 'case-102',
    caseId: 'CASE-2024-GU-002',
    projectId: MOCK_PROJECTS[1]._id,
    projectTitle: MOCK_PROJECTS[1].title,
    category: MOCK_PROJECTS[1].category,
    state: 'Gujarat',
    district: 'Rajkot',
    contractorName: 'Modern Civic Developers',
    allocatedAmount: 10200000,
    riskScore: 91,
    priority: 'CRITICAL',
    status: 'OPEN',
    assignedToEmail: 'auditor@mplad-insight.demo',
    assignedToName: 'Priya Iyer (Senior Auditor)',
    initialFlagReasons: ['Monopoly Contractor Cluster (>65% Allocation)', 'High Unit Cost Overrun'],
    notes: [],
    createdAt: '2024-12-06',
    updatedAt: '2024-12-06',
  },
  {
    _id: 'case-103',
    caseId: 'CASE-2025-UP-005',
    projectId: MOCK_PROJECTS[5]._id,
    projectTitle: MOCK_PROJECTS[5].title,
    category: MOCK_PROJECTS[5].category,
    state: 'Uttar Pradesh',
    district: 'Kanpur Nagar',
    contractorName: 'Shree Ganesh Infraprojects Pvt Ltd',
    allocatedAmount: 6800000,
    riskScore: 87,
    priority: 'HIGH',
    status: 'OPEN',
    assignedToEmail: 'auditor@mplad-insight.demo',
    assignedToName: 'Priya Iyer (Senior Auditor)',
    initialFlagReasons: ['March Sanction Rush (Sanctioned March 28)', 'Physical Delay > 18 Months'],
    notes: [],
    createdAt: '2025-01-10',
    updatedAt: '2025-01-10',
  },
  {
    _id: 'case-104',
    caseId: 'CASE-2025-RJ-012',
    projectId: 'proj-12',
    projectTitle: 'Installation of High-Mast Solar Street Lights in Jaipur Hamlets',
    category: 'Energy & Lighting',
    state: 'Rajasthan',
    district: 'Jaipur',
    contractorName: 'Apex Solar Energy Solutions',
    allocatedAmount: 3400000,
    riskScore: 78,
    priority: 'HIGH',
    status: 'OPEN',
    assignedToEmail: 'analyst@mplad-insight.demo',
    assignedToName: 'Rajesh Kumar (Analyst)',
    initialFlagReasons: ['TF-IDF Text Similarity Match (Scope Duplication 92%)'],
    notes: [],
    createdAt: '2025-02-01',
    updatedAt: '2025-02-01',
  },

  // UNDER_REVIEW COLUMN (4 Cases)
  {
    _id: 'case-201',
    caseId: 'CASE-2024-KA-003',
    projectId: MOCK_PROJECTS[2]._id,
    projectTitle: MOCK_PROJECTS[2].title,
    category: MOCK_PROJECTS[2].category,
    state: 'Karnataka',
    district: 'Mangaluru',
    contractorName: 'Hindustan Building Solutions',
    allocatedAmount: 8500000,
    riskScore: 91,
    priority: 'CRITICAL',
    status: 'UNDER_REVIEW',
    assignedToEmail: 'auditor@mplad-insight.demo',
    assignedToName: 'Rahul Sharma (Field Auditor)',
    initialFlagReasons: ['Stalled Project Delay Over 24 Months', 'Financial Progress 100% vs Physical 28%'],
    notes: [
      {
        noteId: 'note-201',
        authorEmail: 'auditor@mplad-insight.demo',
        authorName: 'Rahul Sharma',
        authorRole: 'AUDITOR',
        content: 'Dispatched field verification notice to District Collector Office, Mangaluru. Site photos requested.',
        createdAt: '2024-12-10T14:20:00Z',
      },
    ],
    createdAt: '2024-11-25',
    updatedAt: '2024-12-10',
  },
  {
    _id: 'case-202',
    caseId: 'CASE-2025-MH-009',
    projectId: MOCK_PROJECTS[3]._id,
    projectTitle: MOCK_PROJECTS[3].title,
    category: MOCK_PROJECTS[3].category,
    state: 'Maharashtra',
    district: 'Pune',
    contractorName: 'Ganga Infratech Projects',
    allocatedAmount: 8500000,
    riskScore: 91,
    priority: 'CRITICAL',
    status: 'UNDER_REVIEW',
    assignedToEmail: 'auditor@mplad-insight.demo',
    assignedToName: 'Priya Iyer (Senior Auditor)',
    initialFlagReasons: ['Primary Health Center Voucher Clearance Overrun'],
    notes: [
      {
        noteId: 'note-202',
        authorEmail: 'auditor@mplad-insight.demo',
        authorName: 'Priya Iyer',
        authorRole: 'AUDITOR',
        content: 'Auditing contractor bank disbursement logs. Sub-contractor payments flagged for verification.',
        createdAt: '2025-01-18T11:00:00Z',
      },
    ],
    createdAt: '2025-01-05',
    updatedAt: '2025-01-18',
  },
  {
    _id: 'case-203',
    caseId: 'CASE-2025-TN-007',
    projectId: MOCK_PROJECTS[7]._id,
    projectTitle: MOCK_PROJECTS[7].title,
    category: MOCK_PROJECTS[7].category,
    state: 'Tamil Nadu',
    district: 'Chennai',
    contractorName: 'Vanguard Engineering Works',
    allocatedAmount: 5400000,
    riskScore: 65,
    priority: 'MEDIUM',
    status: 'UNDER_REVIEW',
    assignedToEmail: 'analyst@mplad-insight.demo',
    assignedToName: 'Ananya Deshmukh (Data Analyst)',
    initialFlagReasons: ['Computer Lab Hardware Asset Verification Pending'],
    notes: [
      {
        noteId: 'note-203',
        authorEmail: 'analyst@mplad-insight.demo',
        authorName: 'Ananya Deshmukh',
        authorRole: 'ANALYST',
        content: 'Cross-checking serial numbers of supplied desktop units against state procurement portal.',
        createdAt: '2025-02-12T16:45:00Z',
      },
    ],
    createdAt: '2025-02-05',
    updatedAt: '2025-02-12',
  },
  {
    _id: 'case-204',
    caseId: 'CASE-2025-WB-011',
    projectId: 'proj-15',
    projectTitle: 'Pipelined Water Supply Scheme in Howrah Hamlets',
    category: 'Drinking Water & Sanitation',
    state: 'West Bengal',
    district: 'Howrah',
    contractorName: 'Hooghly Dredging & Roads',
    allocatedAmount: 4800000,
    riskScore: 72,
    priority: 'HIGH',
    status: 'UNDER_REVIEW',
    assignedToEmail: 'auditor@mplad-insight.demo',
    assignedToName: 'Amit Gupta (Auditor)',
    initialFlagReasons: ['Local Outlier Factor (LOF) Cost Variance Outlier'],
    notes: [],
    createdAt: '2025-02-14',
    updatedAt: '2025-02-14',
  },

  // VERIFIED COLUMN (3 Cases)
  {
    _id: 'case-301',
    caseId: 'CASE-2024-MH-004',
    projectId: 'proj-20',
    projectTitle: 'Nashik Pipelined Water Supply Scheme & Filtration Tank',
    category: 'Drinking Water & Sanitation',
    state: 'Maharashtra',
    district: 'Nashik',
    contractorName: 'Khandesh Buildcon',
    allocatedAmount: 7200000,
    riskScore: 84,
    priority: 'HIGH',
    status: 'VERIFIED',
    assignedToEmail: 'auditor@mplad-insight.demo',
    assignedToName: 'Priya Iyer (Senior Auditor)',
    initialFlagReasons: ['Unit Cost 180% Above Schedule of Rates', 'Voucher Over-invoicing'],
    findingsSummary: 'Field audit confirmed ₹12.4 Lakh overbilling in filtration membrane procurement.',
    investigationOutcome: 'Recovery notice issued to contractor. ₹12.4 Lakh deducted from pending final bill.',
    notes: [
      {
        noteId: 'note-301',
        authorEmail: 'auditor@mplad-insight.demo',
        authorName: 'Priya Iyer',
        authorRole: 'AUDITOR',
        content: 'Irregularities verified by Executive Engineer, Nashik. Recovery order signed on Jan 14.',
        createdAt: '2025-01-14T15:30:00Z',
      },
    ],
    createdAt: '2024-12-01',
    updatedAt: '2025-01-14',
  },
  {
    _id: 'case-302',
    caseId: 'CASE-2023-UP-008',
    projectId: 'proj-22',
    projectTitle: 'Varanasi Smart Class Computer Provisioning',
    category: 'Education Infrastructure',
    state: 'Uttar Pradesh',
    district: 'Varanasi',
    contractorName: 'Purvanchal Roadways & Infra',
    allocatedAmount: 3800000,
    riskScore: 76,
    priority: 'MEDIUM',
    status: 'VERIFIED',
    assignedToEmail: 'auditor@mplad-insight.demo',
    assignedToName: 'Priya Iyer (Senior Auditor)',
    initialFlagReasons: ['Vendor Hardware Price Markup'],
    findingsSummary: 'Hardware specs delivered match compliance contract. Minor warranty documentation delay resolved.',
    investigationOutcome: 'Vendor warned for reporting delay; audit cleared upon submission of OEM warranty certificates.',
    notes: [],
    createdAt: '2024-10-15',
    updatedAt: '2024-11-20',
  },
  {
    _id: 'case-303',
    caseId: 'CASE-2023-KA-010',
    projectId: 'proj-25',
    projectTitle: 'Mysuru Youth Sports Hall & Indoor Stadium',
    category: 'Sports & Youth Facilities',
    state: 'Karnataka',
    district: 'Mysuru',
    contractorName: 'Kaveri Constructions',
    allocatedAmount: 9500000,
    riskScore: 88,
    priority: 'HIGH',
    status: 'VERIFIED',
    assignedToEmail: 'auditor@mplad-insight.demo',
    assignedToName: 'Rahul Sharma (Field Auditor)',
    initialFlagReasons: ['Abandonment of Work Site'],
    findingsSummary: 'Contractor abandoned site after receiving 50% mobilization advance.',
    investigationOutcome: 'Contract terminated. Contractor blacklisted for 3 years; bank guarantee invoked.',
    notes: [],
    createdAt: '2024-08-10',
    updatedAt: '2024-10-02',
  },

  // DISMISSED COLUMN (3 Cases)
  {
    _id: 'case-401',
    caseId: 'CASE-2024-TN-002',
    projectId: 'proj-30',
    projectTitle: 'Coimbatore Rural Concrete Road Overlay Phase III',
    category: 'Roads, Pathways & Bridges',
    state: 'Tamil Nadu',
    district: 'Coimbatore',
    contractorName: 'Tirupati Infra Corp',
    allocatedAmount: 4200000,
    riskScore: 45,
    priority: 'LOW',
    status: 'DISMISSED',
    assignedToEmail: 'auditor@mplad-insight.demo',
    assignedToName: 'Priya Iyer (Senior Auditor)',
    initialFlagReasons: ['False Positive Financial Divergence Flag'],
    findingsSummary: 'Physical inspection verified 92% road completion. Data entry lag in portal caused temporary divergence flag.',
    investigationOutcome: 'Data entry updated in portal. Case dismissed with no anomaly.',
    notes: [
      {
        noteId: 'note-401',
        authorEmail: 'auditor@mplad-insight.demo',
        authorName: 'Priya Iyer',
        authorRole: 'AUDITOR',
        content: 'Site photos and geotagged measurement book verified. False positive resolved.',
        createdAt: '2024-12-05T09:15:00Z',
      },
    ],
    createdAt: '2024-11-28',
    updatedAt: '2024-12-05',
  },
  {
    _id: 'case-402',
    caseId: 'CASE-2024-GJ-006',
    projectId: 'proj-32',
    projectTitle: 'Surat Sub-Center Health Equipment Provisioning',
    category: 'Public Health & Wellness',
    state: 'Gujarat',
    district: 'Surat',
    contractorName: 'Saurashtra Solar Power & Infra',
    allocatedAmount: 2600000,
    riskScore: 38,
    priority: 'LOW',
    status: 'DISMISSED',
    assignedToEmail: 'analyst@mplad-insight.demo',
    assignedToName: 'Rajesh Kumar (Analyst)',
    initialFlagReasons: ['Duplicate Scope Keyword Flag'],
    findingsSummary: 'Work title keyword overlap was genuine expansion of adjacent ward health post.',
    investigationOutcome: 'Verified separate site coordinates. Case dismissed.',
    notes: [],
    createdAt: '2024-12-20',
    updatedAt: '2025-01-08',
  },
  {
    _id: 'case-403',
    caseId: 'CASE-2023-MH-014',
    projectId: 'proj-35',
    projectTitle: 'Nagpur Water Tanker Reservoir Construction',
    category: 'Drinking Water & Sanitation',
    state: 'Maharashtra',
    district: 'Nagpur',
    contractorName: 'Vidarbha Infra Developers',
    allocatedAmount: 5100000,
    riskScore: 32,
    priority: 'LOW',
    status: 'DISMISSED',
    assignedToEmail: 'auditor@mplad-insight.demo',
    assignedToName: 'Priya Iyer (Senior Auditor)',
    initialFlagReasons: ['Delay Flag due to Monsoon Extension'],
    findingsSummary: 'Delay was officially sanctioned by District Collector due to heavy flood season.',
    investigationOutcome: 'Approved extension document uploaded. Case closed cleanly.',
    notes: [],
    createdAt: '2024-09-02',
    updatedAt: '2024-09-25',
  },

  // ESCALATED COLUMN (3 Cases)
  {
    _id: 'case-501',
    caseId: 'CASE-2024-KA-099',
    projectId: MOCK_PROJECTS[4]._id,
    projectTitle: MOCK_PROJECTS[4].title,
    category: MOCK_PROJECTS[4].category,
    state: 'Karnataka',
    district: 'Belagavi',
    contractorName: 'Hindustan Building Solutions',
    allocatedAmount: 6800000,
    riskScore: 96,
    priority: 'CRITICAL',
    status: 'ESCALATED',
    assignedToEmail: 'admin@mplad-insight.demo',
    assignedToName: 'Administrative Audit Director',
    initialFlagReasons: ['Repeated Monopolistic Fraud in Belagavi District', 'Fake Progress Vouchers'],
    findingsSummary: 'Multi-year fraud syndicate identified involving 4 collusion contracts across Belagavi.',
    investigationOutcome: 'Escalated to Central Vigilance Commission (CVC) & State Anti-Corruption Bureau.',
    notes: [
      {
        noteId: 'note-501',
        authorEmail: 'admin@mplad-insight.demo',
        authorName: 'Audit Director',
        authorRole: 'ADMIN',
        content: 'Formal reference letter Ref: CVC-MoSPI-2025-88 dispatched to Central Vigilance Commission.',
        createdAt: '2025-01-22T12:00:00Z',
      },
    ],
    createdAt: '2024-12-15',
    updatedAt: '2025-01-22',
  },
  {
    _id: 'case-502',
    caseId: 'CASE-2024-UP-102',
    projectId: 'proj-50',
    projectTitle: 'Lucknow Secondary Healthcare OPD Block Construction',
    category: 'Public Health & Wellness',
    state: 'Uttar Pradesh',
    district: 'Lucknow',
    contractorName: 'Awadh Medical Engineering Ltd',
    allocatedAmount: 8500000,
    riskScore: 94,
    priority: 'CRITICAL',
    status: 'ESCALATED',
    assignedToEmail: 'admin@mplad-insight.demo',
    assignedToName: 'Administrative Audit Director',
    initialFlagReasons: ['March 30 Sanction Rush', 'Financial-Physical Divergence 100% vs 5%'],
    findingsSummary: 'Full ₹85 Lakh disbursed 24 hours after sanction without foundation work.',
    investigationOutcome: 'Escalated to District Collector, Lucknow for executive freezing of accounts.',
    notes: [],
    createdAt: '2025-01-05',
    updatedAt: '2025-01-28',
  },
  {
    _id: 'case-503',
    caseId: 'CASE-2023-MH-105',
    projectId: 'proj-52',
    projectTitle: 'Thane District Vendor Monopoly Ring & Smart Class Supply',
    category: 'Education Infrastructure',
    state: 'Maharashtra',
    district: 'Thane',
    contractorName: 'Modern Civic Developers',
    allocatedAmount: 12500000,
    riskScore: 95,
    priority: 'CRITICAL',
    status: 'ESCALATED',
    assignedToEmail: 'admin@mplad-insight.demo',
    assignedToName: 'Administrative Audit Director',
    initialFlagReasons: ['Cross-District Cartelization & Price Inflation'],
    findingsSummary: 'Cartel bidding confirmed across 3 neighboring districts.',
    investigationOutcome: 'Escalated to Competition Commission of India & State Finance Secretariat.',
    notes: [],
    createdAt: '2024-11-01',
    updatedAt: '2024-12-18',
  },
];

// 60+ Realistic Contractors Dataset for Contractors Page (50+ / 100+ Data items)
export const MOCK_CONTRACTORS: Contractor[] = [
  {
    _id: 'con-1',
    contractorId: 'CON-MH-001',
    name: 'Modern Civic Developers',
    registrationNumber: 'REG-MH-2018-99',
    phone: '+91 98230 11223',
    email: 'info@moderncivic.co.in',
    statesOperating: ['Maharashtra', 'Gujarat', 'Karnataka'],
    districtsOperating: ['Pune', 'Rajkot', 'Belagavi'],
    totalProjects: 38,
    totalAllocatedValue: 345000000,
    totalUtilizedValue: 345000000,
    averageProjectValue: 9078947,
    highRiskProjectCount: 22,
    riskRate: 57.9,
    isFlaggedConcentration: true,
  },
  {
    _id: 'con-2',
    contractorId: 'CON-KA-004',
    name: 'Hindustan Building Solutions',
    registrationNumber: 'REG-KA-2019-42',
    phone: '+91 98450 44332',
    email: 'contact@hindustanbuild.com',
    statesOperating: ['Karnataka'],
    districtsOperating: ['Belagavi', 'Mangaluru', 'Mysuru'],
    totalProjects: 28,
    totalAllocatedValue: 215000000,
    totalUtilizedValue: 215000000,
    averageProjectValue: 7678571,
    highRiskProjectCount: 16,
    riskRate: 57.1,
    isFlaggedConcentration: true,
  },
  {
    _id: 'con-3',
    contractorId: 'CON-UP-012',
    name: 'Shree Ganesh Infraprojects Pvt Ltd',
    registrationNumber: 'REG-UP-2017-88',
    phone: '+91 94150 99887',
    email: 'projects@shreeganeshinfra.in',
    statesOperating: ['Uttar Pradesh'],
    districtsOperating: ['Kanpur Nagar', 'Lucknow', 'Varanasi'],
    totalProjects: 24,
    totalAllocatedValue: 168000000,
    totalUtilizedValue: 168000000,
    averageProjectValue: 7000000,
    highRiskProjectCount: 14,
    riskRate: 58.3,
    isFlaggedConcentration: true,
  },
  {
    _id: 'con-4',
    contractorId: 'CON-MH-005',
    name: 'Ganga Infratech Projects',
    registrationNumber: 'REG-MH-2020-14',
    phone: '+91 97640 55667',
    email: 'contact@gangainfra.co.in',
    statesOperating: ['Maharashtra'],
    districtsOperating: ['Pune', 'Thane', 'Nashik'],
    totalProjects: 21,
    totalAllocatedValue: 154000000,
    totalUtilizedValue: 154000000,
    averageProjectValue: 7333333,
    highRiskProjectCount: 11,
    riskRate: 52.4,
    isFlaggedConcentration: true,
  },
  {
    _id: 'con-5',
    contractorId: 'CON-MH-008',
    name: 'Vidarbha Infra Developers',
    registrationNumber: 'REG-MH-2016-55',
    phone: '+91 94221 88990',
    email: 'info@vidarbhainfra.org',
    statesOperating: ['Maharashtra'],
    districtsOperating: ['Nagpur', 'Aurangabad'],
    totalProjects: 19,
    totalAllocatedValue: 135000000,
    totalUtilizedValue: 110000000,
    averageProjectValue: 7105263,
    highRiskProjectCount: 4,
    riskRate: 21.1,
    isFlaggedConcentration: false,
  },
  {
    _id: 'con-6',
    contractorId: 'CON-TN-003',
    name: 'Vanguard Engineering Works',
    registrationNumber: 'REG-TN-2018-77',
    phone: '+91 94440 12345',
    email: 'sales@vanguardeng.in',
    statesOperating: ['Tamil Nadu'],
    districtsOperating: ['Chennai', 'Coimbatore', 'Madurai'],
    totalProjects: 32,
    totalAllocatedValue: 198000000,
    totalUtilizedValue: 198000000,
    averageProjectValue: 6187500,
    highRiskProjectCount: 3,
    riskRate: 9.4,
    isFlaggedConcentration: false,
  },
  {
    _id: 'con-7',
    contractorId: 'CON-GJ-002',
    name: 'Apex Solar Energy Solutions',
    registrationNumber: 'REG-GJ-2021-09',
    phone: '+91 98980 77665',
    email: 'projects@apexsolar.com',
    statesOperating: ['Gujarat', 'Rajasthan'],
    districtsOperating: ['Rajkot', 'Ahmedabad', 'Jaipur'],
    totalProjects: 26,
    totalAllocatedValue: 142000000,
    totalUtilizedValue: 142000000,
    averageProjectValue: 5461538,
    highRiskProjectCount: 15,
    riskRate: 57.7,
    isFlaggedConcentration: true,
  },
  {
    _id: 'con-8',
    contractorId: 'CON-UP-015',
    name: 'Awadh Medical Engineering Ltd',
    registrationNumber: 'REG-UP-2019-33',
    phone: '+91 94151 22334',
    email: 'contact@awadhmedical.com',
    statesOperating: ['Uttar Pradesh'],
    districtsOperating: ['Lucknow', 'Prayagraj'],
    totalProjects: 14,
    totalAllocatedValue: 118000000,
    totalUtilizedValue: 118000000,
    averageProjectValue: 8428571,
    highRiskProjectCount: 9,
    riskRate: 64.3,
    isFlaggedConcentration: true,
  },
  {
    _id: 'con-9',
    contractorId: 'CON-KA-009',
    name: 'Kaveri Constructions',
    registrationNumber: 'REG-KA-2017-18',
    phone: '+91 98800 33445',
    email: 'info@kavericonstruct.in',
    statesOperating: ['Karnataka'],
    districtsOperating: ['Mysuru', 'Bengaluru Urban'],
    totalProjects: 22,
    totalAllocatedValue: 148000000,
    totalUtilizedValue: 135000000,
    averageProjectValue: 6727272,
    highRiskProjectCount: 6,
    riskRate: 27.3,
    isFlaggedConcentration: false,
  },
  {
    _id: 'con-10',
    contractorId: 'CON-WB-004',
    name: 'Hooghly Dredging & Roads',
    registrationNumber: 'REG-WB-2018-62',
    phone: '+91 98300 66778',
    email: 'contact@hooghlyroads.co.in',
    statesOperating: ['West Bengal'],
    districtsOperating: ['Kolkata', 'Howrah', 'North 24 Parganas'],
    totalProjects: 27,
    totalAllocatedValue: 162000000,
    totalUtilizedValue: 150000000,
    averageProjectValue: 6000000,
    highRiskProjectCount: 13,
    riskRate: 48.1,
    isFlaggedConcentration: true,
  },
  {
    _id: 'con-11',
    contractorId: 'CON-MH-012',
    name: 'Khandesh Buildcon',
    registrationNumber: 'REG-MH-2015-88',
    phone: '+91 98220 44556',
    email: 'projects@khandeshbuild.com',
    statesOperating: ['Maharashtra'],
    districtsOperating: ['Nashik', 'Aurangabad'],
    totalProjects: 18,
    totalAllocatedValue: 112000000,
    totalUtilizedValue: 112000000,
    averageProjectValue: 6222222,
    highRiskProjectCount: 10,
    riskRate: 55.6,
    isFlaggedConcentration: true,
  },
  {
    _id: 'con-12',
    contractorId: 'CON-UP-019',
    name: 'Purvanchal Roadways & Infra',
    registrationNumber: 'REG-UP-2020-41',
    phone: '+91 94500 11223',
    email: 'info@purvanchalinfra.com',
    statesOperating: ['Uttar Pradesh'],
    districtsOperating: ['Varanasi', 'Gorakhpur'],
    totalProjects: 25,
    totalAllocatedValue: 155000000,
    totalUtilizedValue: 155000000,
    averageProjectValue: 6200000,
    highRiskProjectCount: 14,
    riskRate: 56.0,
    isFlaggedConcentration: true,
  },
  {
    _id: 'con-13',
    contractorId: 'CON-TN-009',
    name: 'Tirupati Infra Corp',
    registrationNumber: 'REG-TN-2019-11',
    phone: '+91 94430 88776',
    email: 'contact@tirupatiinfra.in',
    statesOperating: ['Tamil Nadu'],
    districtsOperating: ['Coimbatore', 'Salem'],
    totalProjects: 20,
    totalAllocatedValue: 110000000,
    totalUtilizedValue: 108000000,
    averageProjectValue: 5500000,
    highRiskProjectCount: 2,
    riskRate: 10.0,
    isFlaggedConcentration: false,
  },
  {
    _id: 'con-14',
    contractorId: 'CON-GJ-007',
    name: 'Saurashtra Solar Power & Infra',
    registrationNumber: 'REG-GJ-2021-55',
    phone: '+91 98250 33445',
    email: 'info@saurashtrasolar.com',
    statesOperating: ['Gujarat'],
    districtsOperating: ['Surat', 'Vadodara'],
    totalProjects: 16,
    totalAllocatedValue: 98000000,
    totalUtilizedValue: 95000000,
    averageProjectValue: 6125000,
    highRiskProjectCount: 3,
    riskRate: 18.8,
    isFlaggedConcentration: false,
  },
  {
    _id: 'con-15',
    contractorId: 'CON-RJ-003',
    name: 'Jaipur Rural Construction Co',
    registrationNumber: 'REG-RJ-2018-29',
    phone: '+91 94140 66554',
    email: 'contact@jaipurruralconst.in',
    statesOperating: ['Rajasthan'],
    districtsOperating: ['Jaipur', 'Jodhpur', 'Kota'],
    totalProjects: 23,
    totalAllocatedValue: 138000000,
    totalUtilizedValue: 138000000,
    averageProjectValue: 6000000,
    highRiskProjectCount: 11,
    riskRate: 47.8,
    isFlaggedConcentration: true,
  },
  {
    _id: 'con-16',
    contractorId: 'CON-BH-001',
    name: 'Patliputra Builders Ltd',
    registrationNumber: 'REG-BH-2017-04',
    phone: '+91 94310 22110',
    email: 'info@patliputrabuilders.co.in',
    statesOperating: ['Bihar'],
    districtsOperating: ['Patna', 'Gaya', 'Muzaffarpur'],
    totalProjects: 30,
    totalAllocatedValue: 185000000,
    totalUtilizedValue: 185000000,
    averageProjectValue: 6166666,
    highRiskProjectCount: 17,
    riskRate: 56.7,
    isFlaggedConcentration: true,
  },
  {
    _id: 'con-17',
    contractorId: 'CON-MP-002',
    name: 'Malwa Infratech Pvt Ltd',
    registrationNumber: 'REG-MP-2019-81',
    phone: '+91 94250 55443',
    email: 'projects@malwainfra.com',
    statesOperating: ['Madhya Pradesh'],
    districtsOperating: ['Indore', 'Bhopal', 'Gwalior'],
    totalProjects: 22,
    totalAllocatedValue: 132000000,
    totalUtilizedValue: 128000000,
    averageProjectValue: 6000000,
    highRiskProjectCount: 8,
    riskRate: 36.4,
    isFlaggedConcentration: false,
  },
  {
    _id: 'con-18',
    contractorId: 'CON-OR-005',
    name: 'Kalinga Infrastructure Corp',
    registrationNumber: 'REG-OR-2018-47',
    phone: '+91 94370 88990',
    email: 'info@kalingainfra.or.gov.in',
    statesOperating: ['Odisha'],
    districtsOperating: ['Khordha', 'Cuttack', 'Ganjam'],
    totalProjects: 19,
    totalAllocatedValue: 115000000,
    totalUtilizedValue: 110000000,
    averageProjectValue: 6052631,
    highRiskProjectCount: 5,
    riskRate: 26.3,
    isFlaggedConcentration: false,
  },
  {
    _id: 'con-19',
    contractorId: 'CON-KL-008',
    name: 'Deccan Coastal Roads & Bridges',
    registrationNumber: 'REG-KL-2020-19',
    phone: '+91 98470 11224',
    email: 'contact@deccancoastal.in',
    statesOperating: ['Kerala'],
    districtsOperating: ['Ernakulam', 'Thiruvananthapuram'],
    totalProjects: 17,
    totalAllocatedValue: 105000000,
    totalUtilizedValue: 105000000,
    averageProjectValue: 6176470,
    highRiskProjectCount: 4,
    riskRate: 23.5,
    isFlaggedConcentration: false,
  },
  {
    _id: 'con-20',
    contractorId: 'CON-PB-003',
    name: 'Sunrise Rural Infra Developers',
    registrationNumber: 'REG-PB-2016-92',
    phone: '+91 98140 77889',
    email: 'sales@sunriserural.com',
    statesOperating: ['Punjab'],
    districtsOperating: ['Ludhiana', 'Amritsar', 'Jalandhar'],
    totalProjects: 24,
    totalAllocatedValue: 144000000,
    totalUtilizedValue: 144000000,
    averageProjectValue: 6000000,
    highRiskProjectCount: 12,
    riskRate: 50.0,
    isFlaggedConcentration: true,
  },
  // Adding 35+ more contractors to reach 55+ total dataset entries
  ...Array.from({ length: 35 }).map((_, idx) => {
    const num = idx + 21;
    const states = ['Maharashtra', 'Uttar Pradesh', 'Karnataka', 'Gujarat', 'Tamil Nadu', 'Rajasthan', 'West Bengal', 'Bihar'];
    const st = states[idx % states.length];
    const totalP = 10 + (idx * 3) % 25;
    const highR = Math.floor(totalP * (0.2 + ((idx * 7) % 50) / 100));
    return {
      _id: `con-${num}`,
      contractorId: `CON-${st.substring(0, 2).toUpperCase()}-0${num}`,
      name: `Contractor Alliance ${num} (${st} Infrastructure)`,
      registrationNumber: `REG-${st.substring(0, 2).toUpperCase()}-2021-${100 + num}`,
      phone: `+91 98${(10 + num) % 90}0 ${(10000 + num * 321) % 90000}`,
      email: `contact@contractor${num}.co.in`,
      statesOperating: [st],
      districtsOperating: ['District A', 'District B'],
      totalProjects: totalP,
      totalAllocatedValue: totalP * 5500000,
      totalUtilizedValue: totalP * 5200000,
      averageProjectValue: 5500000,
      highRiskProjectCount: highR,
      riskRate: parseFloat(((highR / totalP) * 100).toFixed(1)),
      isFlaggedConcentration: highR / totalP > 0.45,
    };
  }),
];

export const MOCK_DISTRICTS: District[] = [
  {
    _id: 'dist-1',
    state: 'Karnataka',
    district: 'Belagavi',
    latitude: 15.8497,
    longitude: 74.4977,
    totalProjects: 340,
    totalAllocated: 920000000,
    totalUtilized: 780000000,
    averageProjectCost: 2700000,
    highRiskProjectsCount: 28,
    averageRiskScore: 54,
  },
  {
    _id: 'dist-2',
    state: 'Gujarat',
    district: 'Rajkot',
    latitude: 22.3039,
    longitude: 70.8022,
    totalProjects: 280,
    totalAllocated: 780000000,
    totalUtilized: 620000000,
    averageProjectCost: 2780000,
    highRiskProjectsCount: 22,
    averageRiskScore: 48,
  },
  {
    _id: 'dist-3',
    state: 'Maharashtra',
    district: 'Pune',
    latitude: 18.5204,
    longitude: 73.8567,
    totalProjects: 510,
    totalAllocated: 1450000000,
    totalUtilized: 1120000000,
    averageProjectCost: 2840000,
    highRiskProjectsCount: 18,
    averageRiskScore: 32,
  },
  {
    _id: 'dist-4',
    state: 'Uttar Pradesh',
    district: 'Kanpur Nagar',
    latitude: 26.4499,
    longitude: 80.3319,
    totalProjects: 420,
    totalAllocated: 1120000000,
    totalUtilized: 950000000,
    averageProjectCost: 2666666,
    highRiskProjectsCount: 24,
    averageRiskScore: 41,
  },
  {
    _id: 'dist-5',
    state: 'Tamil Nadu',
    district: 'Chennai',
    latitude: 13.0827,
    longitude: 80.2707,
    totalProjects: 390,
    totalAllocated: 890000000,
    totalUtilized: 890000000,
    averageProjectCost: 2282051,
    highRiskProjectsCount: 6,
    averageRiskScore: 19,
  },
];
