import { DashboardSummary, Project, AnomalyItem, RiskCase } from '../types';

export const MOCK_PROJECTS: Project[] = [
  {
    _id: 'proj-1',
    projectId: 'MPLAD-2024-KA-BEL-01615',
    title: 'Installation and Development of Irrigation & Rural Electrification',
    description: 'Solar irrigation pump sets and sub-station line extension across rural blocks.',
    category: 'Irrigation & Rural Electrification',
    state: 'Karnataka',
    district: 'Belagavi',
    constituency: 'Belagavi North',
    mpName: 'Mangal Suresh Angadi',
    financialYear: '2024-2025',
    allocatedAmount: 10200000,
    utilizedAmount: 10200000,
    progress: 12,
    status: 'IN_PROGRESS',
    contractorName: 'Modern Civic Developers',
    approvalDate: '2024-11-20',
    riskScore: 91,
    riskLevel: 'CRITICAL',
    confidenceScore: 0.94,
    dimensionScores: {
      financial: 95,
      contractor: 92,
      duplicate: 45,
      geographic: 60,
      temporal: 88,
      efficiency: 92,
      dataQuality: 95,
    },
    signals: [
      {
        ruleId: 'FIN_01',
        dimension: 'FINANCIAL',
        signal: '100% Fund Disbursed vs 12% Physical Progress',
        severity: 'CRITICAL',
        explanation: 'Extreme disbursement divergence with 100% funds released prior to foundation audit.',
      },
    ],
    similarProjects: [],
    recommendation: 'Immediate physical audit and bank account freeze recommendation.',
    createdAt: '2024-11-20',
  },
  {
    _id: 'proj-2',
    projectId: 'MPLAD-2024-GU-RAJ-03315',
    title: 'Installation and Development of Education Infrastructure',
    description: 'Construction of additional classrooms and digital smart labs.',
    category: 'Education Infrastructure',
    state: 'Gujarat',
    district: 'Rajkot',
    constituency: 'Rajkot',
    mpName: 'Parshottam Rupala',
    financialYear: '2024-2025',
    allocatedAmount: 10200000,
    utilizedAmount: 10200000,
    progress: 28,
    status: 'IN_PROGRESS',
    contractorName: 'Modern Civic Developers',
    approvalDate: '2024-12-05',
    riskScore: 91,
    riskLevel: 'CRITICAL',
    confidenceScore: 0.93,
    dimensionScores: {
      financial: 92,
      contractor: 96,
      duplicate: 50,
      geographic: 40,
      temporal: 85,
      efficiency: 90,
      dataQuality: 92,
    },
    signals: [
      {
        ruleId: 'CON_02',
        dimension: 'CONTRACTOR',
        signal: 'Vendor Monopolistic Concentration Cluster',
        severity: 'CRITICAL',
        explanation: 'Modern Civic Developers holds over 65% of allocated funds in Rajkot district.',
      },
    ],
    similarProjects: [],
    recommendation: 'Mandatory cross-district contractor network investigation.',
    createdAt: '2024-12-05',
  },
  {
    _id: 'proj-3',
    projectId: 'MPLAD-2022-KA-MAN-01105',
    title: 'Installation and Development of Roads, Pathways & Bridges',
    description: 'Concrete pathway overlay and bridge culvert repair in coastal hamlets.',
    category: 'Roads, Pathways & Bridges',
    state: 'Karnataka',
    district: 'Mangaluru',
    constituency: 'Dakshina Kannada',
    mpName: 'Nalin Kumar Kateel',
    financialYear: '2022-2023',
    allocatedAmount: 8500000,
    utilizedAmount: 8500000,
    progress: 28,
    status: 'DELAYED',
    contractorName: 'Hindustan Building Solutions',
    approvalDate: '2022-08-14',
    riskScore: 91,
    riskLevel: 'CRITICAL',
    confidenceScore: 0.91,
    dimensionScores: {
      financial: 90,
      contractor: 88,
      duplicate: 82,
      geographic: 55,
      temporal: 94,
      efficiency: 89,
      dataQuality: 90,
    },
    signals: [
      {
        ruleId: 'EFF_03',
        dimension: 'EFFICIENCY',
        signal: 'Stalled Project Delay Over 24 Months',
        severity: 'CRITICAL',
        explanation: 'Work stalled at 28% progress despite full financial allocation 2 years ago.',
      },
    ],
    similarProjects: [],
    recommendation: 'Escalate to District Collectorate for contractor penalty enforcement.',
    createdAt: '2022-08-14',
  },
  {
    _id: 'proj-4',
    projectId: 'MPLAD-2023-MA-PUN-03238',
    title: 'Installation and Development of Public Health & Wellness',
    description: 'Construction of Sub-District Primary Health Center and oxygen plant.',
    category: 'Public Health & Wellness',
    state: 'Maharashtra',
    district: 'Pune',
    constituency: 'Pune',
    mpName: 'Murlidhar Mohol',
    financialYear: '2023-2024',
    allocatedAmount: 8500000,
    utilizedAmount: 8500000,
    progress: 12,
    status: 'IN_PROGRESS',
    contractorName: 'Ganga Infratech Projects',
    approvalDate: '2023-10-10',
    riskScore: 91,
    riskLevel: 'CRITICAL',
    confidenceScore: 0.95,
    dimensionScores: {
      financial: 94,
      contractor: 90,
      duplicate: 75,
      geographic: 60,
      temporal: 92,
      efficiency: 91,
      dataQuality: 94,
    },
    signals: [],
    similarProjects: [],
    recommendation: 'Conduct statutory financial audit of vendor disbursements.',
    createdAt: '2023-10-10',
  },
  {
    _id: 'proj-5',
    projectId: 'MPLAD-2022-KA-BEL-04845',
    title: 'Installation and Development of Skill Development Centers',
    description: 'Establishment of vocational training labs and computer center.',
    category: 'Skill Development Centers',
    state: 'Karnataka',
    district: 'Belagavi',
    constituency: 'Belagavi',
    mpName: 'Jagadish Shettar',
    financialYear: '2022-2023',
    allocatedAmount: 6800000,
    utilizedAmount: 6800000,
    progress: 12,
    status: 'DELAYED',
    contractorName: 'Hindustan Building Solutions',
    approvalDate: '2022-03-29',
    riskScore: 91,
    riskLevel: 'CRITICAL',
    confidenceScore: 0.96,
    dimensionScores: {
      financial: 95,
      contractor: 92,
      duplicate: 80,
      geographic: 65,
      temporal: 96,
      efficiency: 94,
      dataQuality: 96,
    },
    signals: [],
    similarProjects: [],
    recommendation: 'Prioritize physical inspection and verify asset deployment.',
    createdAt: '2022-03-29',
  },
  {
    _id: 'proj-6',
    projectId: 'MPLAD-2021-UT-KAN-04420',
    title: 'Installation and Development of Community Asset & Halls',
    description: 'Multi-purpose panchayat community hall and public library.',
    category: 'Community Asset & Halls',
    state: 'Uttar Pradesh',
    district: 'Kanpur Nagar',
    constituency: 'Kanpur',
    mpName: 'Ramesh Awasthi',
    financialYear: '2021-2022',
    allocatedAmount: 6800000,
    utilizedAmount: 6800000,
    progress: 20,
    status: 'DELAYED',
    contractorName: 'Shree Ganesh Infraprojects Pvt Ltd',
    approvalDate: '2021-09-18',
    riskScore: 87,
    riskLevel: 'CRITICAL',
    confidenceScore: 0.90,
    dimensionScores: {
      financial: 88,
      contractor: 85,
      duplicate: 60,
      geographic: 50,
      temporal: 90,
      efficiency: 88,
      dataQuality: 90,
    },
    signals: [],
    similarProjects: [],
    recommendation: 'Issue notice to contractor and evaluate work cancellation.',
    createdAt: '2021-09-18',
  },
  {
    _id: 'proj-7',
    projectId: 'MPLAD-2024-MH-NGP-00412',
    title: 'Pipelined Water Supply Scheme & Filtration Plant',
    description: 'Sub-surface water intake and pipeline distribution across 4 villages.',
    category: 'Drinking Water & Sanitation',
    state: 'Maharashtra',
    district: 'Nagpur',
    constituency: 'Nagpur',
    mpName: 'Nitin Gadkari',
    financialYear: '2024-2025',
    allocatedAmount: 14500000,
    utilizedAmount: 11200000,
    progress: 78,
    status: 'IN_PROGRESS',
    contractorName: 'Vidarbha Infra Developers',
    approvalDate: '2024-05-12',
    riskScore: 35,
    riskLevel: 'MEDIUM',
    confidenceScore: 0.94,
    dimensionScores: {
      financial: 30,
      contractor: 35,
      duplicate: 15,
      geographic: 20,
      temporal: 40,
      efficiency: 30,
      dataQuality: 96,
    },
    signals: [],
    similarProjects: [],
    recommendation: 'Normal project execution - track scheduled completion.',
    createdAt: '2024-05-12',
  },
  {
    _id: 'proj-8',
    projectId: 'MPLAD-2023-TN-CHN-00891',
    title: 'Smart Class Computers & High-Speed Optical Fiber Network',
    description: 'Hardware provisioning and network cabling for high schools.',
    category: 'Education Infrastructure',
    state: 'Tamil Nadu',
    district: 'Chennai',
    constituency: 'Chennai Central',
    mpName: 'Dayanidhi Maran',
    financialYear: '2023-2024',
    allocatedAmount: 5400000,
    utilizedAmount: 5400000,
    progress: 100,
    status: 'COMPLETED',
    contractorName: 'Vanguard Engineering Works',
    approvalDate: '2023-04-18',
    riskScore: 18,
    riskLevel: 'LOW',
    confidenceScore: 0.98,
    dimensionScores: {
      financial: 15,
      contractor: 12,
      duplicate: 10,
      geographic: 10,
      temporal: 15,
      efficiency: 18,
      dataQuality: 99,
    },
    signals: [],
    similarProjects: [],
    recommendation: 'Verified completed asset - audit closed.',
    createdAt: '2023-04-18',
  },
];

export const MOCK_DASHBOARD_SUMMARY: DashboardSummary = {
  kpis: {
    totalProjects: 5200,
    totalAllocatedAmount: 11732000000,
    totalUtilizedAmount: 848600000,
    avgRiskScore: 24.8,
    criticalRiskCount: 29,
    highRiskCount: 240,
    mediumRiskCount: 146,
    lowRiskCount: 4785,
    totalContractors: 84,
    totalAnomalies: 269,
    openRiskCases: 21,
  },
  charts: {
    riskDistribution: [
      { name: 'Low (0-29)', count: 4785, color: '#10b981' },
      { name: 'Medium (30-59)', count: 146, color: '#f59e0b' },
      { name: 'High (60-79)', count: 240, color: '#f97316' },
      { name: 'Critical (80-100)', count: 29, color: '#ef4444' },
    ],
    categoryBreakdown: [
      { category: 'Drinking Water & Sanitation', count: 1420, totalAllocated: 3450000000, avgRisk: 22 },
      { category: 'Skill Development Centers', count: 680, totalAllocated: 1850000000, avgRisk: 34 },
      { category: 'Education Infrastructure', count: 1150, totalAllocated: 2400000000, avgRisk: 26 },
      { category: 'Sports & Youth Facilities', count: 450, totalAllocated: 980000000, avgRisk: 21 },
      { category: 'Public Health & Wellness', count: 520, totalAllocated: 1250000000, avgRisk: 42 },
      { category: 'Community Asset & Halls', count: 480, totalAllocated: 1100000000, avgRisk: 31 },
      { category: 'Roads, Pathways & Bridges', count: 320, totalAllocated: 480000000, avgRisk: 38 },
      { category: 'Irrigation & Rural Electrification', count: 180, totalAllocated: 222000000, avgRisk: 45 },
    ],
    districtRisk: [
      { state: 'Karnataka', district: 'Belagavi', projectCount: 340, totalAllocated: 920000000, avgRisk: 54, highRiskCount: 28 },
      { state: 'Gujarat', district: 'Rajkot', projectCount: 280, totalAllocated: 780000000, avgRisk: 48, highRiskCount: 22 },
      { state: 'Maharashtra', district: 'Pune', projectCount: 510, totalAllocated: 1450000000, avgRisk: 32, highRiskCount: 18 },
      { state: 'Uttar Pradesh', district: 'Kanpur Nagar', projectCount: 420, totalAllocated: 1120000000, avgRisk: 41, highRiskCount: 24 },
      { state: 'Tamil Nadu', district: 'Chennai', projectCount: 390, totalAllocated: 890000000, avgRisk: 19, highRiskCount: 6 },
    ],
    spendingByYear: [
      { year: '2021-22', allocated: 2800000000, utilized: 2650000000, count: 1200 },
      { year: '2022-23', allocated: 3400000000, utilized: 3100000000, count: 1500 },
      { year: '2023-24', allocated: 3800000000, utilized: 3200000000, count: 1650 },
      { year: '2024-25', allocated: 1732000000, utilized: 848600000, count: 850 },
    ],
  },
  topHighRiskProjects: MOCK_PROJECTS.filter((p) => p.riskLevel === 'CRITICAL' || p.riskLevel === 'HIGH'),
};

export const MOCK_ANOMALIES: AnomalyItem[] = [
  {
    _id: 'anom-1',
    anomalyId: 'ANOM-2024-01615',
    projectId: MOCK_PROJECTS[0]._id,
    projectTitle: MOCK_PROJECTS[0].title,
    state: MOCK_PROJECTS[0].state,
    district: MOCK_PROJECTS[0].district,
    category: MOCK_PROJECTS[0].category,
    contractorName: MOCK_PROJECTS[0].contractorName,
    dimension: 'FINANCIAL',
    ruleId: 'FIN_01',
    signal: '100% Fund Disbursed vs 12% Physical Progress',
    severity: 'CRITICAL',
    score: 91,
    explanation: 'Extreme disbursement divergence with 100% funds released prior to foundation audit.',
    hasInvestigationCase: true,
    riskCaseId: 'case-101',
    createdAt: '2024-11-20',
  },
  {
    _id: 'anom-2',
    anomalyId: 'ANOM-2024-03315',
    projectId: MOCK_PROJECTS[1]._id,
    projectTitle: MOCK_PROJECTS[1].title,
    state: MOCK_PROJECTS[1].state,
    district: MOCK_PROJECTS[1].district,
    category: MOCK_PROJECTS[1].category,
    contractorName: MOCK_PROJECTS[1].contractorName,
    dimension: 'CONTRACTOR',
    ruleId: 'CON_02',
    signal: 'Vendor Monopolistic Concentration Cluster',
    severity: 'CRITICAL',
    score: 91,
    explanation: 'Modern Civic Developers holds over 65% of allocated funds in Rajkot district.',
    hasInvestigationCase: true,
    riskCaseId: 'case-102',
    createdAt: '2024-12-05',
  },
];

export const MOCK_RISK_CASES: RiskCase[] = [
  {
    _id: 'case-101',
    caseId: 'CASE-2024-KA-001',
    projectId: MOCK_PROJECTS[0]._id,
    projectTitle: MOCK_PROJECTS[0].title,
    category: MOCK_PROJECTS[0].category,
    state: MOCK_PROJECTS[0].state,
    district: MOCK_PROJECTS[0].district,
    contractorName: MOCK_PROJECTS[0].contractorName,
    allocatedAmount: MOCK_PROJECTS[0].allocatedAmount,
    riskScore: 91,
    priority: 'CRITICAL',
    status: 'UNDER_REVIEW',
    assignedToEmail: 'auditor@mplad-insight.demo',
    assignedToName: 'Priya Iyer (Senior Auditor)',
    initialFlagReasons: ['100% Fund Disbursed vs 12% Physical Progress', 'Vendor Monopolistic Concentration'],
    notes: [
      {
        noteId: 'note-1',
        authorEmail: 'auditor@mplad-insight.demo',
        authorName: 'Priya Iyer',
        authorRole: 'AUDITOR',
        content: 'Field verification team dispatched to Belagavi. Sub-station component unbuilt despite full 100% voucher clearance.',
        createdAt: '2024-12-01T10:30:00Z',
      },
    ],
    createdAt: '2024-11-22',
    updatedAt: '2024-12-01',
  },
];
