import PDFDocument from 'pdfkit';
import { IProject } from '../models/Project.js';
import { IRiskCase } from '../models/RiskCase.js';

export class ReportGenerator {
  static generateProjectPDF(project: IProject, riskCase?: IRiskCase | null): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ margin: 40, size: 'A4' });
      const buffers: Buffer[] = [];

      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => resolve(Buffer.concat(buffers)));
      doc.on('error', reject);

      // Header Banner
      doc.rect(40, 40, 515, 60).fill('#0f172a');
      doc.fillColor('#ffffff').fontSize(16).text('MPLAD INSIGHT — AUDIT & RISK INTELLIGENCE REPORT', 55, 52);
      doc.fontSize(9).fillColor('#94a3b8').text('MoSPI Scheme Implementation & Anomaly Detection System (PS26102)', 55, 75);

      doc.moveDown(3);
      doc.fillColor('#0f172a');

      // Project Overview Section
      doc.fontSize(13).fillColor('#1e293b').text('1. Project Overview', { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(10).fillColor('#334155');
      doc.text(`Project ID: ${project.projectId}`);
      doc.text(`Title: ${project.title}`);
      doc.text(`Category: ${project.category}`);
      doc.text(`Location: ${project.district}, ${project.state} (Constituency: ${project.constituency || 'N/A'})`);
      doc.text(`Contractor / Vendor: ${project.contractorName}`);
      doc.text(`Sanctioned / Allocated Amount: Rs. ${(project.allocatedAmount || 0).toLocaleString('en-IN')}`);
      doc.text(`Utilized Expenditure: Rs. ${(project.utilizedAmount || 0).toLocaleString('en-IN')} (${project.allocatedAmount > 0 ? ((project.utilizedAmount / project.allocatedAmount) * 100).toFixed(1) : 0}%)`);
      doc.text(`Physical Progress: ${project.progress}% (Status: ${project.status})`);

      doc.moveDown(1.5);

      // AI Risk Intelligence
      doc.fontSize(13).fillColor('#1e293b').text('2. AI Anomaly & Risk Evaluation', { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(10).fillColor('#334155');
      doc.text(`Unified Risk Score: ${project.riskScore} / 100 [Level: ${project.riskLevel}]`);
      doc.text(`Model Confidence / Signal Strength: ${project.confidenceScore}%`);

      doc.moveDown(0.5);
      doc.fontSize(11).fillColor('#475569').text('Flagged Risk Signals & Evidence:');
      if (project.signals && project.signals.length > 0) {
        project.signals.forEach((s, idx) => {
          doc.fontSize(9).fillColor('#b91c1c').text(`• [${s.dimension}] ${s.signal} (${s.severity})`);
          doc.fontSize(8.5).fillColor('#475569').text(`   Explanation: ${s.explanation}`);
        });
      } else {
        doc.fontSize(9).fillColor('#15803d').text('• No critical anomalies or fraud-risk indicators detected.');
      }

      doc.moveDown(1.5);

      // Recommended Action
      doc.fontSize(13).fillColor('#1e293b').text('3. Recommended Audit Action', { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(9.5).fillColor('#0f172a').text(project.recommendation || 'Standard procedural review.');

      // Investigation Case Details if open
      if (riskCase) {
        doc.moveDown(1.5);
        doc.fontSize(13).fillColor('#1e293b').text('4. Investigation Case Record', { underline: true });
        doc.moveDown(0.5);
        doc.fontSize(10).fillColor('#334155');
        doc.text(`Case ID: ${riskCase.caseId} (Status: ${riskCase.status})`);
        doc.text(`Assigned Officer: ${riskCase.assignedToName || 'Unassigned'}`);
        if (riskCase.notes && riskCase.notes.length > 0) {
          doc.text(`Notes Logged: ${riskCase.notes.length} internal investigator note(s).`);
        }
      }

      // Legal Disclaimer Footer
      doc.fontSize(7.5).fillColor('#64748b').text(
        'DISCLAIMER: This document is generated by MPLAD Insight AI Platform for audit-prioritization purposes only. The platform detects anomalies and risk signals. It does not establish legal liability or confirmed fraud. Final determination rests with authorized government audit authorities.',
        40,
        760,
        { width: 515, align: 'center' }
      );

      doc.end();
    });
  }

  static generateProjectCSV(projects: IProject[]): string {
    const headers = [
      'Project ID',
      'Title',
      'Category',
      'State',
      'District',
      'Constituency',
      'Contractor',
      'Allocated Amount (INR)',
      'Utilized Amount (INR)',
      'Progress (%)',
      'Status',
      'Risk Score',
      'Risk Level',
      'Confidence (%)',
      'Signals Count',
      'Recommendation',
    ];

    const rows = projects.map((p) => [
      `"${p.projectId}"`,
      `"${(p.title || '').replace(/"/g, '""')}"`,
      `"${p.category}"`,
      `"${p.state}"`,
      `"${p.district}"`,
      `"${p.constituency || ''}"`,
      `"${(p.contractorName || '').replace(/"/g, '""')}"`,
      p.allocatedAmount,
      p.utilizedAmount,
      p.progress,
      p.status,
      p.riskScore,
      p.riskLevel,
      p.confidenceScore,
      p.signals?.length || 0,
      `"${(p.recommendation || '').replace(/"/g, '""')}"`,
    ]);

    return [headers.join(','), ...rows.map((r) => r.join(','))].join('\n');
  }
}
